apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:v0
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://mysql-service:3306/ecommerce"
            - name: JWT_SECRET
              value: "myDefaultJwtSecretKeyForDevelopmentOnly123456"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 8081